version: "3.4"
services:
  ssl:
    image: itzg/openssl-ubuntu:latest
    volumes:
      - canxium:/canxium
    command: rand -hex 32 | tr -d "\n" > "/canxium/jwt.hex"

  init:
    image: canxium/go-canxium:v0.2.3
    depends_on:
      ssl:
        condition: service_completed_successfully
    volumes:
      - canxium:/canxium
    command: --datadir=/canxium --db.engine=pebble init /genesis/mainnet.genesis.json

  canxium:
    image: canxium/go-canxium:v0.2.3
    restart: always
    volumes:
      - canxium:/canxium
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - "30303:30303"
    command: --syncmode full --http --db.engine=pebble --authrpc.addr 0.0.0.0 --authrpc.jwtsecret=/canxium/jwt.hex --authrpc.vhosts=canxium --networkid 3003 --datadir /canxium --bootnodes enode://314f1041da4b27f5e4c02b4eac52ca7bd2f025cb585490cb7032fdb08db737aa10d7d64a780db697643ece6027d3bc1a511696420e76192648c0d2d74d099c73@boot.canxium.net:30303,enode://767d3e408b073ca501ea7336096c048eea46513ac5c44659ac902d7575881ca114c82277dff7826630ec9fb45d8cfa5a82b9eacc8b477dc475746eaec39e2f2a@boot.canxium.org:30303,enode://f06de34b87954abb25be2e8d592306bc55b396a4eead839dba90baf4e59465d3ef704866962cf2fd995e6ce04f17de31edebb11afcac9df4eaea847f35e3cbaf@boot-n2.canxium.org:30303

  beacon_node:
    image: canxium/prysm:beacon-v5.0.1
    restart: always
    volumes:
      - beacon_node:/data
      - canxium:/canxium
      - logs:/logs
    ports:
      - "3500:3500" # API port
      - "12000:12000" # P2P port
      - "13000:13000" # P2P port
    depends_on:
      ssl:
        condition: service_completed_successfully
      canxium:
        condition: service_started
    command: --datadir=/data --execution-endpoint=http://canxium:8551 --jwt-secret=/canxium/jwt.hex --accept-terms-of-use --verbosity info --canxium --checkpoint-sync-url https://beacon-api.canxium.org --grpc-gateway-host=0.0.0.0 --rpc-host=0.0.0.0

  import_keys:
    image: canxium/prysm:validator-v5.0.1
    volumes:
      - validator:/data
      - ./keystores:/keystores
      - logs:/logs
    command: accounts import --wallet-dir=/data/keystores --keys-dir=/keystores --wallet-password-file=/keystores/password.txt --account-password-file=/keystores/password.txt --accept-terms-of-use

  validator:
    image: canxium/prysm:validator-v5.0.1
    restart: always
    volumes:
      - validator:/data
      - ./keystores:/keystores
      - logs:/logs
    depends_on:
      import_keys:
        condition: service_completed_successfully
      beacon_node:
        condition: service_started
    command: --suggested-fee-recipient 0x0000000000000000000000000000000000000000 --beacon-rpc-provider=beacon_node:4000 --datadir=/data --accept-terms-of-use --wallet-dir=/data/keystores --wallet-password-file=/keystores/password.txt --canxium 

volumes:
  canxium:
  beacon_node:
  validator:
  logs: